### ISSUE TITLE
Is it ready for use now? 

### ISSUE THREAD

**Issue by kexul** [deepmodeling/GROMACS#1]
Hi, I've watched your presentation today, thanks for your work of GPU accelaration for FEP! 

Is this project ready for use now? which branch should I compile to test its functionality? Thanks!

**Comment by AnguseZhang** [comment]
Hi. Thanks for your interest in our work!  Yes,it can be used. But the newest codes are in Gitlab, https://gitlab.com/deepmodeling/gromacs/-/commits/2021.1-gpu-fep-all . You are welcomed to compile and test, which also matters!  Also we can contact and talk via email or Wechat. My email is 352 at pku.edu.cn and my Wechat ID is zyz032189
